repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      #- id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args:
          - --django
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.6.0 # keep synced with pyproject.toml
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8.git
    rev: 5.0.4 # keep synced with pyproject.toml
    hooks:
      - id: flake8
        additional_dependencies: ['importlib-metadata==4.2.0']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782 # keep synced with pyproject.toml
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5 # keep synced with pyproject.toml
    hooks:
      - id: isort
  # - repo: https://gitlab.com/devopshq/gitlab-ci-linter
  #   rev: v1.0.2
  #   hooks:
  #     - id: gitlab-ci-linter
  #       args:
  #         - --server=https://gitlab.com
  #         - --project=37771488
